// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuoteHub.Core.Database;

#nullable disable

namespace QuoteHub.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250413150417_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QuoteHub.Core.Entities.Models.AuthorDBO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("alias");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdon");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("DATETIME")
                        .HasColumnName("dateofbirth");

                    b.Property<int>("Gender")
                        .HasColumnType("INT")
                        .HasColumnName("gender");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedon");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("QuoteHub.Core.Entities.Models.LanguageDBO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdon");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("isocode");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedon");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("QuoteHub.Core.Entities.Models.QuoteDBO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("fk_author_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("createdon");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("isactive");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("CHAR(36)")
                        .HasColumnName("fk_language_id");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5000)")
                        .HasColumnName("quotetext");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updatedon");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("QuoteHub.Core.Entities.Models.QuoteDBO", b =>
                {
                    b.HasOne("QuoteHub.Core.Entities.Models.AuthorDBO", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuoteHub.Core.Entities.Models.LanguageDBO", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
